version: '3'
services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'
    ports:
      - '80:80'
    networks:
      - 'entrepreneurs'
  php:
    build:
      context: .
    image: 'entrepreneurs-rating:1.0'
    networks:
      - 'entrepreneurs'
    volumes:
      - './php.ini:/usr/local/etc/php/conf.d/entrepreneurs.ini'
      - './src:/var/www/html'
networks:
  entrepreneurs:
    name: 'entrepreneurs'